sensei-raw-ctl
==============
:compact-option:

This is a Fork
--------------
The original repo has moved and this is my version

This program makes it possible to change the configuration of your SteelSeries
Sensei Raw mouse from within Linux, *BSD or any other POSIX-compatible system
supported by libusb.

Run `sensei-raw-ctl --help` or `man sensei-raw-ctl` for usage information.

If you don't fancy command line tools, there's also a basic GTK+ frontend
available.  On Ubuntu and its derivatives, you should be able to find it in your
System Settings.

Supported devices
-----------------
 - SteelSeries Sensei Raw
 - SteelSeries Call of Duty: Black Ops II
 - SteelSeries Guild Wars 2

Packages
--------
Regular releases are sporadic.  git master should be stable enough.  You can get
a package with the latest development version from Archlinux's AUR.

Installation
------------
Build dependencies: cmake >= 2.8.5, help2man +
Runtime dependencies: libusb >= 1.0, gtk+ >= 3.0 (optional)

 $ git clone https://git.janouch.name/p/sensei-raw-ctl.git
 $ mkdir sensei-raw-ctl/build
 $ cd sensei-raw-ctl/build
 $ cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Debug
 # make install

Note that there's no `make uninstall` and the GUI needs to be installed in the
right location in order to work correctly.

If you don't want the GUI frontend, append `-DBUILD_GUI=NO` to the `cmake`
command.  The GUI also isn't going to be built if you don't have the GTK+ 3
development packages installed, if your distribution has any.

For Debian-based distros, you can do the following instead of the last step:

 $ cpack -G DEB
 # dpkg -i sensei-raw-ctl-*.deb

Note that for versions of CMake before 2.8.9, you need to prefix `cpack` with
`fakeroot` or file ownership will end up wrong.

Contributing and Support
------------------------
Use https://git.janouch.name/p/sensei-raw-ctl to report bugs, request features,
or submit pull requests.  `git send-email` is tolerated.  If you want to discuss
the project, feel free to join me at ircs://irc.janouch.name, channel #dev.

Bitcoin donations are accepted at: 12r5uEWEgcHC46xd64tt3hHt9EUvYYDHe9

License
-------
This software is released under the terms of the 0BSD license, the text of which
is included within the package along with the list of authors.
